### ISSUE TITLE
CI: disable visual testing for forks

### ISSUE THREAD

**Issue by jsoref** [primer/react#1904]
**Describe the bug**
While  #1786 disabled visual testing for this repository, it left the workflow enabled for forks.

**To Reproduce**
1. Fork this repository
2. Make a change
3. See [error](https://github.com/check-spelling/primer-react/runs/5352132860?check_suite_focus=true)

**Expected behavior**
If a workflow is disabled for the main repository, it shouldn't be enabled for forks.

**Error**
```
Error: TypeError: Cannot read property 'replace' of undefined
    at /home/runner/work/_actions/chromaui/action/v1/action/main.js:2:1611930
    at /home/runner/work/_actions/chromaui/action/v1/action/main.js:2:1610851
    at Object.next (/home/runner/work/_actions/chromaui/action/v1/action/main.js:2:1610956)
    at o (/home/runner/work/_actions/chromaui/action/v1/action/main.js:2:1609670)
Error: Cannot read property 'replace' of undefined
```

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**

**Comment by jsoref** [comment]
I'll send a PR

**Comment by jsoref** [comment]
@lesliecdubs this has a PR...
