### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'btn')

### ISSUE THREAD

**Issue by mohammad-anis** [primer/react#3299]
### Description

Button component is not  working with  "@primer/react": "^35.25.1",
Getting Error , Cannot read properties of undefined (reading 'btn')
TypeError: Cannot read properties of undefined (reading 'btn')
    at getBaseStyles (C:\new-projects\open-banking-fe\node_modules\@primer\react\lib\Button\styles.js:192:75)
    at Object.getButtonStyles (C:\new-projects\open-banking-fe\node_modules\@primer\react\lib\Button\styles.js:276:8)
    at C:\new-projects\open-banking-fe\node_modules\@primer\react\lib\Button\ButtonBase.js:42:47
    at Object.useMemo (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5124:19)
    at Object.useMemo (C:\new-projects\open-banking-fe\node_modules\react\cjs\react.development.js:1650:21)
    at C:\new-projects\open-banking-fe\node_modules\@primer\react\lib\Button\ButtonBase.js:41:28
    at renderWithHooks (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5658:16)
    at renderForwardRef (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5842:18)
    at renderElement (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6005:11)
    at renderNodeDestructiveImpl (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderForwardRef (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5859:5)
    at renderElement (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6005:11)
    at renderNodeDestructiveImpl (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderHostElement (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5642:3)
    at renderElement (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5785:7)
    at renderElement (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderElement (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5971:9)
    at renderNodeDestructiveImpl (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5785:7)
    at renderElement (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderContextProvider (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5920:3)
    at renderElement (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6017:11)
    at renderNodeDestructiveImpl (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5785:7)
    at renderElement (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (C:\new-projects\open-banking-fe\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
error - Error [TypeError]: Cannot read properties of undefined (reading 'btn')

### Steps to reproduce

<Button>Default</Button>
TypeError: Cannot read properties of undefined (reading 'btn')

### Version

35.25.1

### Browser

Chrome

**Comment by joshblack** [comment]
Hi there @mohammad-anis! 👋 Thanks for taking the time to make this issue!

Could you share more information about how to re-create this issue? I tried to use the latest package and import `Button` but was not able to get the error that you're seeing. Any steps to reproduce that you could provide would be incredibly helpful!

**Comment by mohammad-anis** [comment]
Hi @joshblack , 

I think I found the root cause, it is happening because of the custom theme I set in the theme props, but I'm just wondering, how other react-primer components are working.
Here is the codebase for more details.

https://codesandbox.io/s/async-grass-2z950r

Now you can set the customTheme and check the Button component
import { Box,Button } from "@primer/react";
import { ThemeProvider } from '@primer/react';

const customTheme = {
    'default-theme': {
        primary: {
            prim1: 'rgba(40, 60, 106, 1)',
            prim2: 'rgba(40, 60, 106, 0.8)',
            prim3: 'rgba(40, 60, 106, 0.6)',
            prim4: 'rgba(40, 60, 106, 0.4)',
            prim5: 'rgba(40, 60, 106, 0.2)'
        },
        secondary: {
            sec1: 'rgba(141, 58, 64, 1)',
            sec2: 'rgba(141, 58, 64, 0.8)',
            sec3: 'rgba(141, 58, 64, 0.6)',
            sec4: 'rgba(141, 58, 64, 0.4)',
            sec5: 'rgba(141, 58, 64, 0.2)'
        },
        gray: {
            gray100: '#202020',
            gray80: '#495057',
            gray60: '#6D7379',
            gray40: '#92969A',
            gray20: '#B6B9BC',
            gray10: '#DBDCDD',
            gray5: '#EDEEEE'
        },
        system: {
            error: '#BC2E31',
            success: '#6BAA4D',
            warning1: '#FF9C4E',
            warning2: '#FFD462'
        }
    },
};

export default function App() {
  return(
    <ThemeProvider theme= { customTheme } >
     <Box>Hello Primer React</Box>
     <Button>Default</Button>
     </ThemeProvider>
  )
}

**Comment by joshblack** [comment]
Thanks so much for the CodeSandbox! That helps a ton.

For theming, if I remember right the recommendation is to merge the `theme` export from `@primer/react` with your custom theme. For example: https://codesandbox.io/s/jovial-scooby-h1hccg?file=/src/App.tsx. Here is the link to the docs for this concept: https://primer.style/react/theming#customizing-the-theme

Hope that makes sense! Let me know if you have any questions or if I misunderstood anything 😄
